import { Point } from 'geojson'
import * as moment from 'moment';

export interface ProfileMeta {
      _id: string;
      nc_url: string,
      position_qc: number,
      cycle_number: number,
      dac: string,
      date: Date | moment.Moment | string
      date_added?: Date,
      date_qc?: number,
      max_pres?: number,
      bgcMeasKeys?: string[],
      lat: number,
      lon: number,
      platform_number: number,
      geoLocation?: Point,
      station_parameters: string[],
      station_parameters_in_nc?: string[],
      VERTICAL_SAMPLING_SCHEME?: string,
      PI_NAME?: string,
      WMO_INST_TYPE?: string,
      POSITIONING_SYSTEM?: string,
      DATA_MODE?: string,
      PARAMETER_DATA_MODE?: string[],
      DATA_CENTRE?: string,
      DIRECTION?: string,
      PLATFORM_TYPE?: string,
      pres_max_for_TEMP?: number,
      pres_max_for_PSAL?: number,
      pres_min_for_TEMP?: number,
      pres_min_for_PSAL?: number,
      containsBGC?: boolean,
      isDeep?: boolean,
      BASIN?: number, 
      count?: number,
      core_data_mode?: string,
      roundLat?:string,
      roundLon?:string,
      strLat?:string,
      strLon?:string,
      formatted_station_parameters?: string[]
    }

export interface Profile extends ProfileMeta {
    measurements: CoreMeasurements[]
    bgcMeas?: bgcMeasurements[]
}

export interface PlatformMeta {
    _id: number,
    platform_number: number,
    most_recent_date: Date | moment.Moment | string,
    most_recent_date_added: Date | moment.Moment | string,
    number_of_profiles: number,
    POSITIONING_SYSTEM?: string,
    PI_NAME?: string,
    dac: string,
    jcomoppsLink?: string,
    fleetMonitoringLink?: string
}

export interface BgcProfileData {
    _id: string;
    cycle_number: number;
    date: Date;
    lat: number;
    lon: number;
    bgcMeasKeys;
    POSITIONING_SYSTEM;
    bgcMeas: bgcMeasurements[]
}

export interface CoreProfileData {
    _id: string;
    cycle_number: number;
    date: Date;
    POSITIONING_SYSTEM;
    measurements: CoreMeasurements[]
}

export interface CoreMeasurements {
    pres: number
    temp?: number | null, 
    psal?: number | null,
}

export interface StationParameters {
    value: string,
    viewValue: string
  }

export interface ColorScaleSelection {
    value: string
    viewValue: string
  }

export interface bgcMeasurements {
    pres?: number | null,
    pres_qc?: number | null,
    temp?: number | null,
    temp_qc?: number | null,
    psal?: number | null,
    psal_qc?: number | null,
    cndc?: number | null,
    cndc_qc?: number | null,
    doxy?: number | null,
    doxy_qc?: number | null,
    chla?: number | null,
    chla_qc?: number | null,
    cdom?: number | null,
    cdom_qc?: number | null,
    nitrate?: number | null,
    nitrate_qc?: number | null,
    bbp700?: number | null,
    bbp700_qc?: number | null,
    down_irradiance412?: number | null,
    down_irradiance412_qc?: number | null,
    down_irradiance443?: number | null,
    down_irradiance443_qc?: number | null,
    down_irradiance490?: number | null,
    down_irradiance490_qc?: number | null,
    downwelling_par?: number | null,
    downwelling_par_qc?: number | null,
    cfc_12_btl?: number | null,
    cfc_12_btl_qc?: number | null,
    dissolved_organic_carbon_btl?: number | null,
    dissolved_organic_carbon_btl_qc?: number | null,
    total_dissolved_nitrogen_btl?: number | null,
    total_dissolved_nitrogen_btl_qc?: number | null,
    neon_btl?: number | null,
    neon_btl_qc?: number | null,
    cfc_11_btl?: number | null,
    cfc_11_btl_qc?: number | null,
    potential_temperature_68_btl?: number | null,
    potential_temperature_68_btl_qc?: number | null,
    doxy_ctd?: number | null,
    doxy_ctd_qc?: number | null,
    ctd_elapsed_time_ctd?: number | null,
    ctd_elapsed_time_ctd_qc?: number | null,
    tritium_btl?: number | null,
    tritium_btl_qc?: number | null,
    bottle_latitude_btl?: number | null,
    bottle_latitude_btl_qc?: number | null,
    rev_temperature_btl?: number | null,
    rev_temperature_btl_qc?: number | null,
    ctd_beamcp_ctd?: number | null,
    ctd_beamcp_ctd_qc?: number | null,
    ctd_pressure_raw_btl?: number | null,
    ctd_pressure_raw_btl_qc?: number | null,
    partial_co2_temperature_btl?: number | null,
    partial_co2_temperature_btl_qc?: number | null,
    rev_pressure_btl?: number | null,
    rev_pressure_btl_qc?: number | null,
    delta_helium_3_btl?: number | null,
    delta_helium_3_btl_qc?: number | null,
    cfc_113_btl?: number | null,
    cfc_113_btl_qc?: number | null,
    methyl_chloroform_btl?: number | null,
    methyl_chloroform_btl_qc?: number | null,
    total_alkalinity_btl?: number | null,
    total_alkalinity_btl_qc?: number | null,
    bottle_longitude_btl?: number | null,
    bottle_longitude_btl_qc?: number | null,
    hplc_placeholder_btl?: number | null,
    hplc_placeholder_btl_qc?: number | null,
    ctd_transmissometer_raw_ctd?: number | null,
    ctd_transmissometer_raw_ctd_qc?: number | null,
    dissolved_organic_nitrogen_btl?: number | null,
    dissolved_organic_nitrogen_btl_qc?: number | null,
    tritium_error_btl?: number | null,
    tritium_error_btl_qc?: number | null,
    del_carbon_13_dic_btl?: number | null,
    del_carbon_13_dic_btl_qc?: number | null,
    ammonium_btl?: number | null,
    ammonium_btl_qc?: number | null,
    del_oxygen_18_error_btl?: number | null,
    del_oxygen_18_error_btl_qc?: number | null,
    oxygen_btl?: number | null,
    oxygen_btl_qc?: number | null,
    ctd_fluor_arbitrary_ctd?: number | null,
    ctd_fluor_arbitrary_ctd_qc?: number | null,
    ctd_transmissometer_ctd?: number | null,
    ctd_transmissometer_ctd_qc?: number | null,
    radium_228_btl?: number | null,
    radium_228_btl_qc?: number | null,
    ctd_fluor_raw_btl?: number | null,
    ctd_fluor_raw_btl_qc?: number | null,
    ctd_temperature_68_ctd?: number | null,
    ctd_temperature_68_ctd_qc?: number | null,
    oxygen_ml_l_btl?: number | null,
    oxygen_ml_l_btl_qc?: number | null,
    ctd_fluor_raw_ctd?: number | null,
    ctd_fluor_raw_ctd_qc?: number | null,
    phosphate_btl?: number | null,
    phosphate_btl_qc?: number | null,
    silicate_btl?: number | null,
    silicate_btl_qc?: number | null,
    rev_temperature_90_btl?: number | null,
    rev_temperature_90_btl_qc?: number | null,
    delta_helium_3_error_btl?: number | null,
    delta_helium_3_error_btl_qc?: number | null,
    total_carbon_btl?: number | null,
    total_carbon_btl_qc?: number | null,
    neon_error_btl?: number | null,
    neon_error_btl_qc?: number | null,
    carbon_tetrachloride_btl?: number | null,
    carbon_tetrachloride_btl_qc?: number | null,
    ctd_number_of_observations_ctd?: number | null,
    ctd_number_of_observations_ctd_qc?: number | null,
    fco2_btl?: number | null,
    fco2_btl_qc?: number | null,
    ph_sws_btl?: number | null,
    ph_sws_btl_qc?: number | null,
    chlorophyll_a_ug_kg_btl?: number | null,
    chlorophyll_a_ug_kg_btl_qc?: number | null,
    helium_btl?: number | null,
    helium_btl_qc?: number | null,
    ref_temperature_c_btl?: number | null,
    ref_temperature_c_btl_qc?: number | null,
    del_oxygen_18_btl?: number | null,
    del_oxygen_18_btl_qc?: number | null,
    chlorophyll_a_btl?: number | null,
    chlorophyll_a_btl_qc?: number | null,
    particulate_organic_nitrogen_btl?: number | null,
    particulate_organic_nitrogen_btl_qc?: number | null,
    potential_temperature_btl?: number | null,
    potential_temperature_btl_qc?: number | null,
    nitrate_btl?: number | null,
    nitrate_btl_qc?: number | null,
    par_ctd?: number | null,
    par_ctd_qc?: number | null,
    psal_ctd?: number | null,
    psal_ctd_qc?: number | null,
    radium_226_btl?: number | null,
    radium_226_btl_qc?: number | null,
    rev_temperature_c_btl?: number | null,
    rev_temperature_c_btl_qc?: number | null,
    temp_ctd?: number | null,
    temp_ctd_qc?: number | null,
    ctd_oxygen_ml_l_ctd?: number | null,
    ctd_oxygen_ml_l_ctd_qc?: number | null,
    nitrite_btl?: number | null,
    nitrite_btl_qc?: number | null,
    ctd_fluor_ctd?: number | null,
    ctd_fluor_ctd_qc?: number | null,
    salinity_btl?: number | null,
    salinity_btl_qc?: number | null,
    bottle_time_btl?: number | null,
    bottle_time_btl_qc?: number | null,
    partial_pressure_of_co2_btl?: number | null,
    partial_pressure_of_co2_btl_qc?: number | null,
    del_carbon_14_dic_btl?: number | null,
    del_carbon_14_dic_btl_qc?: number | null,
    psal_btl?: number | null,
    psal_btl_qc?: number | null,
    ph_total_h_scale_btl?: number | null,
    ph_total_h_scale_btl_qc?: number | null,
    phaeophytin_ug_l_btl?: number | null,
    phaeophytin_ug_l_btl_qc?: number | null,
    ctd_temperature_unk_btl?: number | null,
    ctd_temperature_unk_btl_qc?: number | null,
    del_carbon_14_dic_error_btl?: number | null,
    del_carbon_14_dic_error_btl_qc?: number | null,
    helium_error_btl?: number | null,
    helium_error_btl_qc?: number | null,
    ctd_transmissometer_raw_btl?: number | null,
    ctd_transmissometer_raw_btl_qc?: number | null,
    sulfur_hexifluoride_btl?: number | null,
    sulfur_hexifluoride_btl_qc?: number | null,
    temp_btl?: number | null,
    temp_btl_qc?: number | null,
    ph_temperature_btl?: number | null,
    ph_temperature_btl_qc?: number | null,
    phaeophytin_btl?: number | null,
    phaeophytin_btl_qc?: number | null,
    potential_temperature_c_btl?: number | null,
    potential_temperature_c_btl_qc?: number | null,
    ctd_temperature_unk_ctd?: number | null,
    ctd_temperature_unk_ctd_qc?: number | null,
    doxy_btl?: number | null,
    doxy_btl_qc?: number | null,
    fco2_temperature_btl?: number | null,
    fco2_temperature_btl_qc?: number | null,
    sample_btl?: number | null,
    sample_btl_qc?: number | null,
    nitrous_oxide_btl?: number | null,
    nitrous_oxide_btl_qc?: number | null,
    particulate_organic_carbon_btl?: number | null,
    particulate_organic_carbon_btl_qc?: number | null,
    sample_ctd?: number | null,
    sample_ctd_qc?: number | null,
    bottle_number_btl?: number | null,
    bottle_number_btl_qc?: number | null,
    nitrite_nitrate_btl?: number | null,
    nitrite_nitrate_btl_qc?: number | null,
    ref_temperature_btl?: number | null,
    ref_temperature_btl_qc?: number | null,    
}

export interface DataArrays {
    x1: number[], 
    x1_qc?: number[], 
    x2_qc?: number[],
    x2: number[],
    x1_label: string,
    x2_label: string,
    _id: string[], 
    _ids: string[], 
    cycle: number[], 
    time: string[],
}
