version: '3'
services:
  argo-express:
    build: . #specify the directory of the Dockerfile
    restart: always
    ports: 
    - '3000:3000' # specify port forwarding
    links:
    - database
  database:
    image: mongo:4.2.3  # specify image to build container from
    restart: always
    ports:
      - '127.0.0.1:27018:27018' # include localhost ip to restrict access to localhost
    volumes:
      # - /storage/mongodb:/data/db:Z # development
      - C:\Users\vivas\argovis\mongodb:/data/db:Z # production
  #netdata:
    #image: netdata/netdata 
    #restart: always
    #hostname: example.com # set to fqdn of host
    #ports:
      #- 19999:19999
    #cap_add:
     #- SYS_PTRACE
    #security_opt:
     # - apparmor:unconfined
    #volumes:
      #- /proc:/host/proc:ro
      #- /sys:/host/sys:ro
      #- /var/run/docker.sock:/var/run/docker.sock:ro
